import type { POIConfig } from "../types/poi"

// Updated default XPath to match Python code
export const DEFAULT_XPATH =
  '//*[@id="QA0Szd"]/div/div/div[1]/div[2]/div/div[1]/div/div/div[2]/div/div[1]/div[2]/div/div[2]/span[1]/span/button'

export const CATEGORY_CONFIGS: Record<string, POIConfig> = {
  school: {
    text_query_template: "schools in {}",
    poi_names: { uf1: "school", uf2: "school", surrounding: "school", filtered: "school" },
    apply_within_logic: true,
    required_types_api: ["school"],
    rating_count_threshold: 0,
    name_filter_exclude: [
      "playschool",
      "play school",
      "preschool",
      "pre school",
      "kindergarten",
      "kinder garten",
      "nursery",
      "day care",
      "daycare",
      "coaching",
      "tuition",
      "kid",
      "kids",
      "kidz",
    ],
    use_selenium: true,
    selenium_xpath: DEFAULT_XPATH, // Use the Python default
    primary_type_filter_mode: "exclude",
    primary_type_filter_list: [
      "Preschool",
      "Kindergarten School",
      "Music school",
      "Coaching Center",
      "Day care center",
      "Nursery school",
      "Education center",
      "Mathematics school",
      "Aerobics Class",
      "Studying center",
      "Educational consultant",
    ],
  },
  hospital: {
    text_query_template: "hospitals and medical institution in {}",
    poi_names: { uf1: "hospital", uf2: "hospital", surrounding: "hospital", filtered: "hospital" },
    apply_within_logic: true,
    required_types_api: ["hospital", "college", "university"],
    rating_count_threshold: 10,
    name_filter_exclude: ["pet", "clinic", "nursing home", "blood bank", "bloodbank", "blood donation", "store"],
    use_selenium: true,
    selenium_xpath: DEFAULT_XPATH, // Use the Python default
    primary_type_filter_mode: "include",
    primary_type_filter_list: [
      "Hospital",
      "Private hospital",
      "General hospital",
      "Government hospital",
      "Cancer treatment center",
      "Medical school",
      "Medical Centre",
      "Medical Center",
      "Public Medical Centre",
    ],
  },
  hotel: {
    text_query_template: "5 star hotels in {}",
    poi_names: { uf1: "hotel", uf2: "hotel", surrounding: "hotel", filtered: "hotel" },
    apply_within_logic: true,
    required_types_api: ["hotel"],
    rating_count_threshold: 10,
    name_filter_exclude: [],
    use_selenium: true,
    selenium_xpath: "//*[@id='QA0Szd']/div/div/div[1]/div[2]/div/div[1]/div/div/div[2]/div/div[1]/div[2]/div/div/span/span/span/span[2]/span/span",
    primary_type_filter_mode: "include",
    primary_type_filter_list: ["5-star hotel", "4-star hotel"],
  },
  shopping_mall: {
    text_query_template: "shopping malls in {}",
    poi_names: { uf1: "shopping_mall", uf2: "shopping_mall", surrounding: "shopping_mall", filtered: "shopping_mall" },
    required_types_api: ["shopping_mall"],
    rating_count_threshold: 10,
    name_filter_exclude: ["plaza", "complex"],
    apply_within_logic: true,
    use_selenium: false,
    primary_type_filter_mode: "none",
    primary_type_filter_list: [],
  },
  college: {
    text_query_template: "colleges and universities in {}",
    poi_names: { uf1: "college", uf2: "college", surrounding: "college", filtered: "college" },
    apply_within_logic: true,
    required_types_api: ["college", "university"],
    rating_count_threshold: 10,
    name_filter_exclude: [],
    use_selenium: false,
    primary_type_filter_mode: "none",
    primary_type_filter_list: [],
  },
  metro: {
    text_query_template: "metro station in {}",
    poi_names: { uf1: "metro_station", uf2: "metro_station", surrounding: "metro_station", filtered: "metro_station" },
    apply_within_logic: false,
    required_types_api: ["subway_station"],
    rating_count_threshold: 5,
    name_filter_exclude: [],
    use_selenium: true,
    selenium_xpath: DEFAULT_XPATH, // Use the Python default
    primary_type_filter_mode: "include",
    primary_type_filter_list: ["Subway station"],
  },
  railway: {
    text_query_template: "train station in {}",
    poi_names: {
      uf1: "railway_station",
      uf2: "railway_station",
      surrounding: "railway_station",
      filtered: "railway_station",
    },
    apply_within_logic: false,
    required_types_api: ["train_station"],
    rating_count_threshold: 5,
    name_filter_exclude: [],
    use_selenium: true,
    selenium_xpath: DEFAULT_XPATH, 
    primary_type_filter_mode: "include",
    primary_type_filter_list: ["Train station"],
  },
  tourism: {
    text_query_template: "tourist attraction in {}",
    poi_names: {
      uf1: "tourist_attraction",
      uf2: "tourist_attraction",
      surrounding: "tourist_attraction",
      filtered: "tourist_attraction",
    },
    apply_within_logic: true,
    required_types_api: ["tourist_attraction"],
    rating_count_threshold: 100,
    name_filter_exclude: [],
    use_selenium: false,
    primary_type_filter_mode: "none",
    primary_type_filter_list: [],
  },
  market: {
    text_query_template: "famous major market in {}",
    poi_names: { uf1: "market", uf2: "market", surrounding: "market", filtered: "market" },
    apply_within_logic: true,
    required_types_api: ["market"],
    rating_count_threshold: 500,
    name_filter_exclude: [
      "fish",
      "vegetable",
      "sabji",
      "weekly",
      "budh",
      "sunday",
      "monday",
      "tuesday",
      "wednesday",
      "thursday",
      "friday",
      "saturday",
    ],
    use_selenium: false,
    primary_type_filter_mode: "none",
    primary_type_filter_list: [],
  },
  park: {
    text_query_template: "park in {}",
    poi_names: { uf1: "park", uf2: "park", surrounding: "park", filtered: "park" },
    apply_within_logic: true,
    required_types_api: ["park"],
    rating_count_threshold: 10,
    name_filter_exclude: [],
    use_selenium: false,
    primary_type_filter_mode: "none",
    primary_type_filter_list: [],
  },
  residential_society: {
    text_query_template: "Residential Society in {}",
    poi_names: {
      uf1: "Residential Societies",
      uf2: "Residential Societies",
      surrounding: "Residential Societies",
      filtered: "Residential Societies",
    },
    apply_within_logic: true,
    required_types_api: [
      "apartment_complex",
      "housing_complex",
      "apartment_building",
      "condominium_complex",
    ],
    rating_count_threshold: 10,
    name_filter_exclude: [],
    use_selenium: false,
    primary_type_filter_mode: "none",
    primary_type_filter_list: [],
  },
  office: {
    text_query_template: "Office complex in {}",
    poi_names: {
      uf1: "office",
      uf2: "Office",
      surrounding: "Office Complex",
      filtered: "Office complex",
    },
    apply_within_logic: true,
    required_types_api: ["corporate_office", "business_center"],
    rating_count_threshold: 10,
    name_filter_exclude: [],
    use_selenium: false,
    primary_type_filter_mode: "none",
    primary_type_filter_list: [],
  },
}

export const CITY_SYNONYMS: Record<string, string[]> = {
  "Bangalore": ["Bangalore", "Bengaluru"],
    "Bengaluru": ["Bangalore", "Bengaluru"],
    "Noida": ["Noida"],
    "Greater Noida":["Greater Noida"],
    "Kolkata": ["Kolkata", "Calcutta"],
    "Calcutta" : ["Kolkata", "Calcutta"],
    "Hyderabad": ["Hyderabad", "Hyd"],
    "Navi Mumbai": ["Navi Mumbai", "New Mumbai", "Mumbai Navi"],
    "Pune": ["Pune", "Poona"],
    "Ghaziabad": ["Ghaziabad", "Gzb"],
    "Delhi": ["Delhi", "New Delhi", "NCR"],
    "Gurugram": ["Gurugram", "Gurgaon", "Gurugram NCR"],
    "Gurgaon": ["Gurugram", "Gurgaon", "Gurugram NCR"],
    "Mumbai Thane": ["Mumbai Thane", "Thane", "Thane Mumbai", "Mumbai Metropolitan"],
    "Mumbai": ["Mumbai", "Bombay", "Bambai"],
    "Chennai": ["Chennai", "Madras"],
    "Ahmedabad": ["Ahmedabad", "Amdavad"],
    "Ahmedabad (All)" : ["Ahmedabad", "Amdavad"],
    "Faridabad": ["Faridabad", "Fbd", "Faridabad NCR"],
    "Chandigarh": ["Chandigarh"],
    "Coimbatore": ["Coimbatore", "Kovai"],
    "Kochi": ["Kochi", "Cochin"],
    "Jaipur": ["Jaipur", "Pink City"],
    "Lucknow": ["Lucknow"],
    "Bhubaneswar": ["Bhubaneswar"],
    "Mohali": ["Mohali", "SAS Nagar","Sahibzada Ajit Singh Nagar"],
    "Surat": ["Surat"],
    "Vadodara": ["Vadodara", "Baroda"],
    "Bhopal": ["Bhopal"],
    "Dehradun": ["Dehradun", "Dehra Dun","Dera Dun"],
    "Indore": ["Indore"],
    "Nagpur": ["Nagpur"],
    "Patna": ["Patna","Pataliputra","Azimabad"],
    "Visakhapatnam": ["Visakhapatnam", "Vizag"],
    "Panchkula": ["Panchkula"],
    "Nasik": ["Nasik", "Nashik"],
    "Nashik" : ["Nashik", "Nasik"],
    "Mysore": ["Mysore", "Mysuru"],
    "Ranchi": ["Ranchi","Ranci"],
    "Raipur": ["Raipur"],
    "Vijayawada": ["Vijayawada", "Bezawada"],
    "Varanasi": ["Varanasi", "Banaras", "Benaras", "Kashi"],
    "Aurangabad": ["Aurangabad", "Chhatrapati Sambhajinagar"],
    "Ernakulam": ["Ernakulam", "Cochin", "Kochi"],
    "Rajkot": ["Rajkot"],
    "Madurai": ["Madurai"],
    "Guwahati": ["Guwahati", "Gauhati"],
    "Pondicherry": ["Pondicherry", "Puducherry","Pondichery"],
    "Calicut": ["Calicut", "Kozhikode"]
}
